# lightning.pytorch==2.0.9
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  gnn: null
  tasks: null
  optimizer_class: torch.optim.Adam
  optimizer_kwargs: null
  scheduler_class: null
  scheduler_kwargs: null
  scheduler_config: null
data:
  db: null
  pulsemaps: null
  graph_definition: null
  features: null
  truth: null
  batch_size: null
  train_shuffle: true
  selection: null
  num_workers: 10
  persistent_workers: true
  node_truth: null
  truth_table: truth
  node_truth_table: null
  string_selection: null
  loss_weight_table: null
  loss_weight_column: null
  index_column: event_no
  labels: null
ckpt_path: null
